---
- name: "add node JS"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "install node JS"
  become: true
  abt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install PM2"
  npm:
    name: pm2
    global: yes
    
  