---
- name: Create backend-app Directory
  file:
    path: ~/backend-app
    state: directory


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: Start the app
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
    
  register: execute_node

- name: Enable pm2
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
