---
- name: Create backend  Directory
  file:
    path: ~/backend
    state: directory


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm i

- name: Start the app
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: Enable pm2
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
